name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-internal:
    runs-on: self-hosted
    steps:
      - name: Pull and Rebuild on eai.taipit.ru
        run: |
          cd /opt/eai/taipit-eai-hub
          git pull origin main
          docker compose up -d --build
